---
- hosts: webserver
  become: True
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: ansible-devops/index.html
        dest: /var/wwww/html/
